[package]
name = "adventofcode2021"
version = "0.1.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2018"
# edition = "2021" # can't be used with current ghaction-rust-coverage version

[dependencies]
anyhow = "1"
sqrid = "0"
# sqrid = { git = "https://github.com/lpenz/sqrid", branch = "devel" }
nom = "7"
itertools = "0"
lazy_static = "1"
